services:
  postgres:
    image: postgres:14-alpine
    container_name: grc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: grc-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/grc_db
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_change_in_production
      - JWT_EXPIRES_IN=1h
      - CORS_ORIGIN=*
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 5 &&
        npm run setup:db &&
        npm start
      "

volumes:
  postgres_data:
